services:
  vault:
    image: hashicorp/vault:1.15
    container_name: vibetradingbotv5-vault
    entrypoint: [ "vault" ]
    ports:
      - "8200:18200"
    cap_add:
      - IPC_LOCK
    volumes:
      - vault_data:/vault/file
      - ./vault.hcl:/vault/config/vault.hcl:ro
    command: [ "server", "-config=/vault/config/vault.hcl" ]

  postgres:
    image: postgres:16
    container_name: vibetradingbotv5-postgres
    env_file:
      - .env.prod.local
    ports:
      - "5440:5432"
    volumes:
      - pgdata_prod:/var/lib/postgresql/data

  postgres-test:
    image: postgres:16
    container_name: vibetradingbotv5-postgres-test
    env_file:
      - ./.env.test.local
    ports:
      - "5441:5432"
    volumes:
      - pgdata_test:/var/lib/postgresql/data

volumes:
  pgdata_prod:
  pgdata_test:
  vault_data:
