spring.datasource.url=jdbc:postgresql://localhost:5440/tradingbot
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.flyway.enabled=true
server.port=8080
okx.base-url=https://www.okx.com
okx.api-key=${OKX_API_KEY:}
okx.secret-key=${OKX_SECRET_KEY:}
okx.passphrase=${OKX_PASSPHRASE:}
