-- Шаг 4: account-state snapshot баланса (REFRESH_BALANCE). balance_containers
-- (account-level) + balances (currency-level, FK balance_container_id,
-- replace semantics). Не trading entity: нет status/lifecycle. Денежные
-- величины — numeric(36,18); время — UTC. Схема —
-- docs/models/domain/core/BalanceContainer.md, docs/models/mapping/Balance.md.

create table balance_containers (
    id                       bigint generated by default as identity primary key,
    exchange_id              bigint not null,
    external_updated_at      timestamptz,
    external_total_equity    numeric(36, 18),
    external_adjusted_equity numeric(36, 18),
    external_available_equity numeric(36, 18),
    created_at               timestamptz,
    created_by               varchar(64),
    modified_at              timestamptz,
    modified_by              varchar(64),
    external_created_at      timestamptz,
    external_modified_at     timestamptz,
    constraint uk_balance_container_exchange unique (exchange_id),
    constraint fk_balance_container_exchange foreign key (exchange_id) references exchanges (id)
);

create table balances (
    id                        bigint generated by default as identity primary key,
    balance_container_id      bigint      not null,
    external_currency         varchar(32) not null,
    external_updated_at       timestamptz,
    external_equity           numeric(36, 18),
    external_cash_balance     numeric(36, 18),
    external_available_balance numeric(36, 18),
    external_frozen_balance   numeric(36, 18),
    created_at                timestamptz,
    created_by                varchar(64),
    modified_at               timestamptz,
    modified_by               varchar(64),
    external_created_at       timestamptz,
    external_modified_at      timestamptz,
    constraint fk_balance_container foreign key (balance_container_id) references balance_containers (id)
);

-- Индекс под findByBalanceContainerId / deleteByBalanceContainerId (replace на каждый REFRESH_BALANCE).
create index ix_balance_container on balances (balance_container_id);
