-- Шаг 6: механика финализации сделки. deal_finalization_states —
-- persisted retry-state финализационных команд (FINALIZE_ENTRY /
-- FINALIZE_EXIT / MARK_CLOSED / MARK_ERROR), отдельная сущность от
-- deal_action_states (финализация не привязана к StrategyAction,
-- ретраится по-командно — DEAL-Q1). last_error — jsonb; enum'ы строкой;
-- время UTC (timestamptz). По одной строке на (deal, type) —
-- идемпотентность финализации через upsert по ключу. Схема —
-- docs/models/domain/other/DealFinalizationState.md.

create table deal_finalization_states (
    id            bigint generated by default as identity primary key,
    deal_id       bigint      not null,
    type          varchar(32) not null,
    status        varchar(32) not null,
    attempt_count integer,
    max_attempts  integer,
    next_retry_at timestamptz,
    last_error    jsonb,
    -- Идемпотентность финализации: одно состояние на финализационную команду сделки.
    constraint uk_deal_finalization_state_deal_type unique (deal_id, type),
    constraint fk_deal_finalization_state_deal foreign key (deal_id) references deals (id)
);

-- Индексы под горячие выборки оркестрации (шаг 6): активные сделки за проход
-- (DealOrchestratorJob) и gatekeeper входа по инструменту (EntryScannerJob /
-- DealOpeningService). Таблица deals не пруним — индексы по status/instrument
-- держат выборку активных дешёвой по мере роста истории закрытых сделок.
create index ix_deal_status on deals (status);
create index ix_deal_instrument_status on deals (instrument_id, status);

-- Инвариант «одна незакрытая сделка на инструмент» на уровне БД (defense-in-depth
-- к gatekeeper'у): частичный уникальный индекс по активным статусам.
create unique index uk_deal_active_instrument on deals (instrument_id)
    where status not in ('CLOSED', 'EMERGENCY_CLOSED');
