package com.example.tradingbot.domain.model.commands;

public enum ServiceCommandType {

    REFRESH_BALANCE,

    REFRESH_POSITION,
    CLOSE_POSITION,

    CREATE_ORDER,
    SUBMIT_ORDER,
    AMEND_ORDER,
    CANCEL_ORDER,
    REFRESH_ORDER,
    REFRESH_PENDING_ORDERS,
    REFRESH_ORDER_HISTORY,

    CREATE_ALGO_ORDER,
    SUBMIT_ALGO_ORDER,
    AMEND_ALGO_ORDER,
    CANCEL_ALGO_ORDER,
    REFRESH_ALGO_ORDER,
    REFRESH_ALGO_ORDERS,
    REFRESH_ALGO_ORDER_HISTORY,

    REFRESH_FILLS,

    FINALIZE_DEAL_ENTRY,
    FINALIZE_DEAL_EXIT,
    MARK_DEAL_CLOSED,
    MARK_DEAL_ERROR,

    EXECUTE_KILL_SWITCH
}
