-- Шаг 6 (реактивные холды L3/L4): anomaly_reports — журнал safety-инцидента.
-- Носитель before/after-слепков состояния (internal/external × before/after)
-- вокруг встроенного kill-switch и точка severity-политики блокировки
-- торговли (enforcement — на статусе инструмента/биржи, не здесь). Четыре
-- слепка — jsonb; enum'ы (scope/status/severity) строкой; время UTC
-- (timestamptz). scope (INSTRUMENT/EXCHANGE) снимает неоднозначность
-- instrument_id=null. Схема — docs/models/domain/other/AnomalyReport.md,
-- lifecycle — docs/lifecycles/AnomalyReport.md.

create table anomaly_reports (
    id                   bigint generated by default as identity primary key,
    internal_id          varchar(64) not null,
    exchange_id          bigint      not null,
    instrument_id        bigint,
    scope                varchar(16) not null,
    status               varchar(32) not null,
    severity             varchar(16) not null,
    code                 varchar(64) not null,
    message              varchar(1024),
    internal_before      jsonb,
    external_before      jsonb,
    internal_after       jsonb,
    external_after       jsonb,
    created_at           timestamptz,
    created_by           varchar(64),
    modified_at          timestamptz,
    modified_by          varchar(64),
    external_created_at  timestamptz,
    external_modified_at timestamptz,
    constraint uk_anomaly_report_internal_id unique (internal_id)
);
