-- Разделение сделки и транша (шаг 7 фазы 1).
--
-- Стадии входа и сопровождения переезжают со сделки на ТРАНШ: сделка
-- ведёт агрегат (ACTIVE / EXIT_PENDING / ERROR / CLOSED /
-- EMERGENCY_CLOSED), транш — свой жизненный цикл (PRECHECK …CLOSED).
--
-- Проект до запуска: таблицы пусты, бэкфилл не требуется, обязательные
-- колонки вводятся ALTER'ом напрямую
-- (.claude/rules/pre-launch-schema-changes.md).

create table deal_tranches (
    id                 bigint generated by default as identity primary key,
    internal_id        varchar(64) not null,
    deal_id            bigint      not null,
    status             varchar(32) not null,
    -- Номер эпизода: растёт при переоткрытии ТЕМ ЖЕ траншем. Операнд
    -- области «эпизод» — без него строки прошлого эпизода неотличимы от
    -- строк текущего.
    episode_seq        integer     not null default 1,
    -- Слагаемые экспозиции; сама экспозиция производна и не хранится.
    entry_filled       numeric(36, 18),
    reduce_only_filled numeric(36, 18),
    protection_closed  numeric(36, 18),
    created_at         timestamptz,
    updated_at         timestamptz,
    constraint uk_deal_tranche_internal_id unique (internal_id),
    constraint fk_deal_tranche_deal foreign key (deal_id) references deals (id)
);

create index ix_deal_tranche_deal on deal_tranches (deal_id);

-- Заявки принадлежат траншу; deal_id остаётся агрегатным представлением
-- для teardown уровня сделки.
alter table orders add column deal_tranche_id bigint;
alter table orders add constraint fk_order_deal_tranche
    foreign key (deal_tranche_id) references deal_tranches (id);
create index ix_order_deal_tranche on orders (deal_tranche_id);

alter table algo_orders add column deal_tranche_id bigint;
alter table algo_orders add constraint fk_algo_order_deal_tranche
    foreign key (deal_tranche_id) references deal_tranches (id);
create index ix_algo_order_deal_tranche on algo_orders (deal_tranche_id);

-- Строка исполнения стратегийного действия: транш и номер его эпизода.
-- Пусто у исполнений УРОВНЯ СДЕЛКИ (агрегатная поверхность стратегии).
alter table deal_action_states add column deal_tranche_id bigint;
alter table deal_action_states add column tranche_episode_seq integer;
alter table deal_action_states add constraint fk_deal_action_state_deal_tranche
    foreign key (deal_tranche_id) references deal_tranches (id);

-- Прежний ключ мерил состояние СДЕЛКИ и не различал ни транша, ни
-- эпизода: одно объявление действия, материализованное N траншами,
-- конфликтовало бы само с собой.
alter table deal_action_states drop constraint uk_deal_action_state_deal_action;

-- Ключи ЧАСТИЧНЫЕ, по живым статусам: завершённые строки уникальность не
-- держат. Форма — две, потому что NULL в уникальном индексе Postgres сам
-- с собой НЕ конфликтует: индекс по трём колонкам пропустил бы два живых
-- исполнения одного агрегатного действия.
create unique index uk_deal_action_state_tranche_live
    on deal_action_states (deal_id, deal_tranche_id, tranche_episode_seq, strategy_action_id)
    where deal_tranche_id is not null
      and status not in ('COMPLETED', 'FAILED', 'CANCELED');

create unique index uk_deal_action_state_deal_level_live
    on deal_action_states (deal_id, strategy_action_id)
    where deal_tranche_id is null
      and status not in ('COMPLETED', 'FAILED', 'CANCELED');

create index ix_deal_action_state_deal on deal_action_states (deal_id);

-- Шаги стратегии группируются статусом ТРАНША, а не сделки.
alter table strategy_steps rename column deal_status to tranche_status;
alter index uk_strategy_step_detail_status_index rename to uk_strategy_step_detail_tranche_status_index;

-- Переоткрытие эпизода транша — настройка стратегии (эталон её объявляет).
-- Пусто читается как «не допускает»: разрешение объявляется явно.
alter table strategy_details add column position_reopen_allowed boolean;
