-- Шаг 1: поток рыночных данных. Таблицы exchanges / instruments /
-- candle_groups / candles. Время — UTC (timestamptz). Денежные
-- величины — numeric(36,18) (PriceConstants).

create table exchanges (
    id                   bigint generated by default as identity primary key,
    internal_id          varchar(64)  not null,
    name                 varchar(64)  not null,
    base_url             varchar(255) not null,
    status               varchar(32)  not null,
    created_at           timestamptz,
    created_by           varchar(64),
    modified_at          timestamptz,
    modified_by          varchar(64),
    external_created_at  timestamptz,
    external_modified_at timestamptz,
    constraint uk_exchange_internal_id unique (internal_id),
    constraint uk_exchange_name unique (name)
);

create table instruments (
    id                        bigint generated by default as identity primary key,
    internal_id               varchar(64)  not null,
    exchange_id               bigint       not null,
    external_id               varchar(64)  not null,
    external_type             varchar(32)  not null,
    status                    varchar(32)  not null,
    external_status           varchar(32),
    margin_mode               varchar(16)  not null,
    external_margin_mode      varchar(16),
    leverage                  integer      not null,
    external_leverage         varchar(32),
    planned_candle_start_date bigint,
    created_at                timestamptz,
    created_by                varchar(64),
    modified_at               timestamptz,
    modified_by               varchar(64),
    external_created_at       timestamptz,
    external_modified_at      timestamptz,
    constraint uk_instrument_internal_id unique (internal_id),
    constraint uk_instrument_exchange_id_external_id unique (exchange_id, external_id),
    constraint fk_instrument_exchange foreign key (exchange_id) references exchanges (id)
);

create table candle_groups (
    id                      bigint generated by default as identity primary key,
    internal_id             varchar(128) not null,
    instrument_id           bigint       not null,
    timeframe               varchar(32)  not null,
    external_timeframe      varchar(16)  not null,
    status                  varchar(32)  not null,
    actual_first_utc_millis bigint,
    actual_last_utc_millis  bigint,
    count                   bigint       not null default 0,
    created_at              timestamptz,
    created_by              varchar(64),
    modified_at             timestamptz,
    modified_by             varchar(64),
    external_created_at     timestamptz,
    external_modified_at    timestamptz,
    constraint uk_candle_group_internal_id unique (internal_id),
    constraint uk_candle_group_instrument_timeframe unique (instrument_id, timeframe),
    constraint fk_candle_group_instrument foreign key (instrument_id) references instruments (id)
);

create table candles (
    id                   bigint generated by default as identity primary key,
    candle_group_id      bigint         not null,
    open_timestamp       bigint         not null,
    open                 numeric(36, 18) not null,
    high                 numeric(36, 18) not null,
    low                  numeric(36, 18) not null,
    close                numeric(36, 18) not null,
    volume               numeric(36, 18),
    created_at           timestamptz,
    created_by           varchar(64),
    modified_at          timestamptz,
    modified_by          varchar(64),
    external_created_at  timestamptz,
    external_modified_at timestamptz,
    constraint uk_candle_group_id_open_timestamp unique (candle_group_id, open_timestamp),
    constraint fk_candle_candle_group foreign key (candle_group_id) references candle_groups (id)
);
