-- Объявления траншей и узкая агрегатная поверхность шагов (шаг 7 фазы 1).
--
-- Поведение входа объявляется ТРАНШЕМ, а не деталью: из одного
-- объявления с level_count = N материализуется N траншей, различающихся
-- уровнем. На самой детали остаётся только узкая агрегатная поверхность
-- (шаги EXIT / FAIL_SAFE уровня сделки).
--
-- Проект до запуска: таблицы пусты, бэкфилл не требуется, обязательные
-- колонки вводятся ALTER'ом напрямую
-- (.claude/rules/pre-launch-schema-changes.md).

create table strategy_tranches (
    id                      bigint generated by default as identity primary key,
    strategy_detail_id      bigint      not null,
    key                     varchar(64) not null,
    -- Умолчания нет: пустое место мажорировалось бы единицей, то есть в
    -- разрешающую сторону неравенства статического запаса
    -- (docs/rules/risk-policy.md).
    level_count             integer     not null,
    level_step              numeric(36, 18),
    position_reopen_allowed boolean,
    created_at              timestamptz,
    created_by              varchar(64),
    modified_at             timestamptz,
    modified_by             varchar(64),
    external_created_at     timestamptz,
    external_modified_at    timestamptz,
    constraint uk_strategy_tranche_detail_key unique (strategy_detail_id, key),
    constraint ck_strategy_tranche_level_count check (level_count >= 1),
    -- Смещение уровня осмысленно только у сетки и обязательно у неё.
    constraint ck_strategy_tranche_level_step
        check ((level_count > 1) = (level_step is not null)),
    constraint fk_strategy_tranche_detail
        foreign key (strategy_detail_id) references strategy_details (id)
);

-- Шаг принадлежит либо траншу, либо детали. Уровень объявления читается
-- по тому, на кого строка ссылается, а не по типу шага: тип — предмет
-- проверки создания, а не носитель уровня.
alter table strategy_steps add column strategy_tranche_id bigint;
alter table strategy_steps add constraint fk_strategy_step_tranche
    foreign key (strategy_tranche_id) references strategy_tranches (id);

alter table strategy_steps alter column strategy_detail_id drop not null;
alter table strategy_steps alter column tranche_status drop not null;
alter table strategy_steps add column deal_status varchar(32);

-- Прежний ключ мерил деталь и не различал транша: N объявлений с шагами
-- одного статуса конфликтовали бы по step_index.
alter table strategy_steps drop constraint uk_strategy_step_detail_tranche_status_index;

create unique index uk_strategy_step_tranche_status_index
    on strategy_steps (strategy_tranche_id, tranche_status, step_index)
    where strategy_tranche_id is not null;

create unique index uk_strategy_step_detail_deal_status_index
    on strategy_steps (strategy_detail_id, deal_status, step_index)
    where strategy_detail_id is not null;

-- Ровно один родитель и ровно один ключ группировки — вместе, одним
-- ограничением: строка с обоими родителями попала бы в оба уникальных
-- индекса и читалась бы двумя уровнями сразу.
alter table strategy_steps add constraint ck_strategy_step_single_owner
    check (
        (strategy_tranche_id is not null and tranche_status is not null
             and strategy_detail_id is null and deal_status is null)
        or (strategy_detail_id is not null and deal_status is not null
             and strategy_tranche_id is null and tranche_status is null)
    );

-- Признак переоткрытия уехал на транш: он свойство одного входа, а не
-- всей фазы.
alter table strategy_details drop column position_reopen_allowed;

-- Уровень — свойство транша, а не действия: сетку задаёт шаблон
-- объявления (docs/models/domain/aggregate/Strategy.md §StrategyTranche).
alter table strategy_actions drop column level;

-- Транш сделки знает своё объявление и свой уровень в сетке. Пусто у
-- восстановленного транша: объявления у него нет вовсе.
alter table deal_tranches add column strategy_tranche_id bigint;
alter table deal_tranches add column level integer;
alter table deal_tranches add column entry_step_type varchar(64);
alter table deal_tranches add column close_reason varchar(64);
alter table deal_tranches add constraint fk_deal_tranche_strategy_tranche
    foreign key (strategy_tranche_id) references strategy_tranches (id);

-- Одно объявление × один уровень материализуется в один НЕТЕРМИНАЛЬНЫЙ
-- транш: закрытые уровень не держат и переоткрытию не мешают.
create unique index uk_deal_tranche_declaration
    on deal_tranches (deal_id, strategy_tranche_id, level)
    where strategy_tranche_id is not null and status <> 'CLOSED';

create index ix_deal_tranche_deal_status on deal_tranches (deal_id, status);

-- Тип входного шага описывает вход ТРАНША, а не сделки: у сетки входов
-- столько же, сколько уровней.
alter table deals drop column entry_step_type;

comment on column strategy_tranches.level_count is
    'Сколько экземпляров материализовать: 1 — один транш, больше — сетка';

comment on column deal_tranches.level is
    'Уровень экземпляра в сетке объявления; смещает цену входа на level × level_step';
