-- Шаг 2: стратегия. Реляционный каркас immutable-дерева Strategy
-- (strategies / strategy_market_phase_settings / strategy_details /
-- strategy_steps / strategy_actions + таблицы видов, JOINED) + JSONB-навес
-- (настройки рыночных данных, params, условие шага, политика
-- устаревания, вложенные настройки действий). Денежные/процентные
-- величины — numeric(36,18) (PriceConstants); enum'ы — строкой;
-- duration — ISO-8601 строкой; имена таблиц — во множественном числе
-- (общее правило проекта). Схема — docs/models/domain/aggregate/
-- Strategy.md §Персистентность, docs/decisions/strategy-tree-persistence.md.

create table strategies (
    id                   bigint generated by default as identity primary key,
    internal_id          varchar(64)  not null,
    instrument_id        bigint       not null,
    name                 varchar(128) not null,
    status               varchar(32)  not null,
    created_at           timestamptz,
    created_by           varchar(64),
    modified_at          timestamptz,
    modified_by          varchar(64),
    external_created_at  timestamptz,
    external_modified_at timestamptz,
    constraint uk_strategy_internal_id unique (internal_id),
    constraint fk_strategy_instrument foreign key (instrument_id) references instruments (id)
);

-- Инвариант lifecycle: одна ACTIVE стратегия на инструмент.
create unique index uk_strategy_active_per_instrument
    on strategies (instrument_id)
    where status = 'ACTIVE';

create table strategy_market_phase_settings (
    id                        bigint generated by default as identity primary key,
    strategy_id               bigint      not null,
    timeframe                 varchar(32) not null,
    params                    jsonb       not null,
    indicator_settings        jsonb,
    market_structure_settings jsonb,
    expiration_duration       varchar(32) not null,
    created_at                timestamptz,
    created_by                varchar(64),
    modified_at               timestamptz,
    modified_by               varchar(64),
    external_created_at       timestamptz,
    external_modified_at      timestamptz,
    constraint uk_strategy_market_phase_setting_strategy unique (strategy_id),
    constraint fk_strategy_market_phase_setting_strategy foreign key (strategy_id) references strategies (id)
);

create table strategy_details (
    id                        bigint generated by default as identity primary key,
    strategy_id               bigint          not null,
    market_phase_type         varchar(32)     not null,
    phase_entry_policy        varchar(32)     not null,
    risk_per_trade_percent    numeric(36, 18),
    target_risk_reward_ratio  numeric(36, 18),
    indicator_settings        jsonb,
    market_structure_settings jsonb,
    created_at                timestamptz,
    created_by                varchar(64),
    modified_at               timestamptz,
    modified_by               varchar(64),
    external_created_at       timestamptz,
    external_modified_at      timestamptz,
    constraint uk_strategy_detail_strategy_phase unique (strategy_id, market_phase_type),
    constraint fk_strategy_detail_strategy foreign key (strategy_id) references strategies (id)
);

create table strategy_steps (
    id                          bigint generated by default as identity primary key,
    strategy_detail_id          bigint      not null,
    deal_status                 varchar(32) not null,
    step_index                  integer     not null,
    step_type                   varchar(32) not null,
    condition                   jsonb       not null,
    market_data_expired_setting jsonb       not null,
    created_at                  timestamptz,
    created_by                  varchar(64),
    modified_at                 timestamptz,
    modified_by                 varchar(64),
    external_created_at         timestamptz,
    external_modified_at        timestamptz,
    constraint uk_strategy_step_detail_status_index unique (strategy_detail_id, deal_status, step_index),
    constraint fk_strategy_step_detail foreign key (strategy_detail_id) references strategy_details (id)
);

create table strategy_actions (
    id                   bigint generated by default as identity primary key,
    strategy_step_id     bigint      not null,
    strategy_detail_id   bigint      not null,
    action_kind          varchar(32) not null,
    key                  varchar(64) not null,
    action_type          varchar(32) not null,
    level                integer,
    target_action_key    varchar(64),
    target_action_id     bigint,
    created_at           timestamptz,
    created_by           varchar(64),
    modified_at          timestamptz,
    modified_by          varchar(64),
    external_created_at  timestamptz,
    external_modified_at timestamptz,
    constraint uk_strategy_action_detail_key unique (strategy_detail_id, key),
    constraint fk_strategy_action_step foreign key (strategy_step_id) references strategy_steps (id),
    constraint fk_strategy_action_detail foreign key (strategy_detail_id) references strategy_details (id),
    -- Self-FK резолвится при сохранении дерева; deferrable — порядок
    -- вставки строк действий внутри транзакции не ограничивает.
    constraint fk_strategy_action_target foreign key (target_action_id) references strategy_actions (id)
        deferrable initially deferred,
    -- Нет self-loop (NULL проходит по семантике CHECK).
    constraint ck_strategy_action_no_self_target check (target_action_id <> id)
);

create table strategy_order_actions (
    id                     bigint primary key,
    order_type             varchar(32) not null,
    direction              varchar(16) not null,
    allocation_percents    numeric(36, 18),
    position_reducing_only boolean,
    placement              jsonb,
    attached_protection    jsonb,
    constraint fk_strategy_order_action_base foreign key (id) references strategy_actions (id)
);

create table strategy_algo_order_actions (
    id                      bigint primary key,
    condition_type          varchar(32) not null,
    stop_loss_settings      jsonb,
    trailing_settings       jsonb,
    close_fraction_percents numeric(36, 18),
    trigger_profit_percents numeric(36, 18),
    trigger_price_type      varchar(16),
    constraint fk_strategy_algo_order_action_base foreign key (id) references strategy_actions (id)
);

-- Вырожденная подтаблица вида POSITION (собственных полей нет) —
-- допустимо при JOINED (strategy-tree-persistence.md §Действия).
create table strategy_position_actions (
    id bigint primary key,
    constraint fk_strategy_position_action_base foreign key (id) references strategy_actions (id)
);
