-- Шаг 3: производные рыночные данные (индикаторы / структура / фаза).
-- Реестры конфигураций (indicator_configs / market_structure_configs) —
-- идентичность считаемого (тип + timeframe + canonical-params), на них
-- ссылаются результаты по config_id (шаринг по идентичности). Результаты:
-- indicator_values (SINGLE_TABLE по типам индикатора), market_structures
-- + market_price_levels, market_phases (ключ — контейнер-настройка,
-- осознанное исключение). Денежные/процентные величины — numeric(36,18)
-- (PriceConstants); enum'ы — строкой; время — UTC (timestamptz). Имена
-- таблиц — во множественном числе. Схема —
-- docs/decisions/market-data-result-identity-keying.md,
-- docs/models/domain/other/{IndicatorValue,MarketStructure,MarketPhase}.md.

-- Условная фаза: MarketPhaseParams распущен, на его месте — авторские
-- клаузы phaseRules (JSONB). Персистентных стратегий ещё нет, поэтому
-- замена колонки безопасна (docs/decisions/market-phase-conditional-classification.md).
alter table strategy_market_phase_settings drop column params;
alter table strategy_market_phase_settings add column phase_rules jsonb not null;

create table indicator_configs (
    id                   bigint generated by default as identity primary key,
    indicator_type       varchar(32) not null,
    timeframe            varchar(32) not null,
    params_canonical     text        not null,
    created_at           timestamptz,
    created_by           varchar(64),
    modified_at          timestamptz,
    modified_by          varchar(64),
    external_created_at  timestamptz,
    external_modified_at timestamptz,
    constraint uk_indicator_config_identity unique (indicator_type, timeframe, params_canonical)
);

create table market_structure_configs (
    id                   bigint generated by default as identity primary key,
    timeframe            varchar(32) not null,
    params_canonical     text        not null,
    created_at           timestamptz,
    created_by           varchar(64),
    modified_at          timestamptz,
    modified_by          varchar(64),
    external_created_at  timestamptz,
    external_modified_at timestamptz,
    constraint uk_market_structure_config_identity unique (timeframe, params_canonical)
);

-- Значения индикаторов: одна таблица на все типы (SINGLE_TABLE),
-- дискриминатор indicator_type; значения наследников — nullable-колонки.
create table indicator_values (
    id                   bigint generated by default as identity primary key,
    indicator_type       varchar(32)     not null,
    instrument_id        bigint          not null,
    config_id            bigint          not null,
    candle_timestamp     timestamptz     not null,
    atr                  numeric(36, 18),
    ema                  numeric(36, 18),
    rsi                  numeric(36, 18),
    macd_line            numeric(36, 18),
    signal_line          numeric(36, 18),
    histogram            numeric(36, 18),
    upper_band           numeric(36, 18),
    middle_band          numeric(36, 18),
    lower_band           numeric(36, 18),
    bandwidth            numeric(36, 18),
    percent_b            numeric(36, 18),
    stoch_k              numeric(36, 18),
    stoch_d              numeric(36, 18),
    obv                  numeric(36, 18),
    efficiency_ratio     numeric(36, 18),
    created_at           timestamptz,
    created_by           varchar(64),
    modified_at          timestamptz,
    modified_by          varchar(64),
    external_created_at  timestamptz,
    external_modified_at timestamptz,
    constraint uk_indicator_value_identity unique (instrument_id, config_id, candle_timestamp),
    constraint fk_indicator_value_config foreign key (config_id) references indicator_configs (id)
);

create index ix_indicator_value_latest on indicator_values (instrument_id, config_id, candle_timestamp desc);

create table market_structures (
    id                          bigint generated by default as identity primary key,
    instrument_id               bigint          not null,
    config_id                   bigint          not null,
    type                        varchar(32)     not null,
    window_start_at             timestamptz     not null,
    window_end_at               timestamptz     not null,
    confirmed_at                timestamptz,
    breakout_broken_level_type  varchar(32),
    breakout_direction          varchar(16),
    breakout_level_price        numeric(36, 18),
    breakout_confirmed_at       timestamptz,
    created_at                  timestamptz,
    created_by                  varchar(64),
    modified_at                 timestamptz,
    modified_by                 varchar(64),
    external_created_at         timestamptz,
    external_modified_at        timestamptz,
    constraint uk_market_structure_identity unique (instrument_id, config_id, window_end_at),
    constraint fk_market_structure_config foreign key (config_id) references market_structure_configs (id)
);

create index ix_market_structure_latest on market_structures (instrument_id, config_id, window_end_at desc);

create table market_price_levels (
    id                   bigint generated by default as identity primary key,
    market_structure_id  bigint          not null,
    type                 varchar(32)     not null,
    price                numeric(36, 18) not null,
    detected_at          timestamptz,
    confirmed_at         timestamptz,
    created_at           timestamptz,
    created_by           varchar(64),
    modified_at          timestamptz,
    modified_by          varchar(64),
    external_created_at  timestamptz,
    external_modified_at timestamptz,
    constraint fk_market_price_level_structure foreign key (market_structure_id)
        references market_structures (id) on delete cascade
);

create index ix_market_price_level_structure on market_price_levels (market_structure_id);

create table market_phases (
    id                               bigint generated by default as identity primary key,
    instrument_id                    bigint      not null,
    strategy_market_phase_setting_id bigint      not null,
    type                             varchar(32) not null,
    candle_timestamp                 timestamptz not null,
    confirmed_at                     timestamptz,
    created_at                       timestamptz,
    created_by                       varchar(64),
    modified_at                      timestamptz,
    modified_by                      varchar(64),
    external_created_at              timestamptz,
    external_modified_at             timestamptz,
    constraint uk_market_phase_identity unique (instrument_id, strategy_market_phase_setting_id, candle_timestamp),
    constraint fk_market_phase_setting foreign key (strategy_market_phase_setting_id)
        references strategy_market_phase_settings (id)
);

create index ix_market_phase_latest
    on market_phases (instrument_id, strategy_market_phase_setting_id, candle_timestamp desc);
