ALTER TABLE instrument
    ADD COLUMN IF NOT EXISTS last_price VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS mark_price VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS index_price VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS price_updated_at TIMESTAMPTZ NULL;

ALTER TABLE position
    ADD COLUMN IF NOT EXISTS pos VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS avg_px VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS mark_px VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS liq_px VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS lever VARCHAR(32) NULL,
    ADD COLUMN IF NOT EXISTS mgn_mode VARCHAR(16) NULL,
    ADD COLUMN IF NOT EXISTS upl VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS u_time BIGINT NULL;

ALTER TABLE "order"
    ADD COLUMN IF NOT EXISTS state VARCHAR(32) NULL,
    ADD COLUMN IF NOT EXISTS ord_type VARCHAR(32) NULL,
    ADD COLUMN IF NOT EXISTS px VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS sz VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS fill_sz VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS avg_px VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS fee VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS c_time BIGINT NULL,
    ADD COLUMN IF NOT EXISTS u_time BIGINT NULL;

ALTER TABLE algo_order
    ADD COLUMN IF NOT EXISTS state VARCHAR(32) NULL,
    ADD COLUMN IF NOT EXISTS algo_type VARCHAR(32) NULL,
    ADD COLUMN IF NOT EXISTS sz VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS trigger_px VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS ord_px VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS tp_trigger_px VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS tp_ord_px VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS sl_trigger_px VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS sl_ord_px VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS callback_ratio VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS callback_spread VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS c_time BIGINT NULL,
    ADD COLUMN IF NOT EXISTS u_time BIGINT NULL;
