-- Трек D, этап B: настройки рыночных данных промоутятся в собственные
-- strategy-scope-строки (объявляются раз, UNIQUE(strategy_id, key)),
-- результаты расчёта ключуются настройкой-владельцем (config_id →
-- setting_id), реестры конфигураций и шаринг по идентичности убраны.
-- Персистентных стратегий ещё нет — изменение схемы безопасно. См.
-- docs/decisions/strategy-tree-persistence.md (§Ревизия — настройки в
-- собственные строки), docs/decisions/market-data-result-identity-keying.md.

-- 1. Листовые настройки — собственные таблицы strategy-scope.
create table strategy_indicator_settings (
    id                  bigint generated by default as identity primary key,
    strategy_id         bigint      not null,
    key                 varchar(64) not null,
    indicator_type      varchar(32) not null,
    params              jsonb       not null,
    destiny             varchar(32) not null,
    expiration_duration varchar(32) not null,
    constraint uk_strategy_indicator_setting_key unique (strategy_id, key),
    constraint fk_strategy_indicator_setting_strategy foreign key (strategy_id) references strategies (id)
);

create table strategy_market_structure_settings (
    id                   bigint generated by default as identity primary key,
    strategy_id          bigint      not null,
    key                  varchar(64) not null,
    timeframe            varchar(32) not null,
    efficiency_ratio_key varchar(64),
    atr_key              varchar(64),
    params               jsonb       not null,
    destiny              varchar(32) not null,
    expiration_duration  varchar(32) not null,
    constraint uk_strategy_market_structure_setting_key unique (strategy_id, key),
    constraint fk_strategy_market_structure_setting_strategy foreign key (strategy_id) references strategies (id)
);

-- 2. JSONB-настройки на контейнерах больше не нужны (настройки — на стратегии).
alter table strategy_market_phase_settings drop column indicator_settings;
alter table strategy_market_phase_settings drop column market_structure_settings;
alter table strategy_details drop column indicator_settings;
alter table strategy_details drop column market_structure_settings;

-- 3. Результаты: config_id → setting_id (owner-ключевание).
drop index ix_indicator_value_latest;
alter table indicator_values drop constraint fk_indicator_value_config;
alter table indicator_values drop constraint uk_indicator_value_identity;
alter table indicator_values rename column config_id to strategy_indicator_setting_id;
alter table indicator_values add constraint fk_indicator_value_setting
    foreign key (strategy_indicator_setting_id) references strategy_indicator_settings (id);
alter table indicator_values add constraint uk_indicator_value_owner
    unique (instrument_id, strategy_indicator_setting_id, candle_timestamp);
create index ix_indicator_value_latest
    on indicator_values (instrument_id, strategy_indicator_setting_id, candle_timestamp desc);

drop index ix_market_structure_latest;
alter table market_structures drop constraint fk_market_structure_config;
alter table market_structures drop constraint uk_market_structure_identity;
alter table market_structures rename column config_id to strategy_market_structure_setting_id;
alter table market_structures add constraint fk_market_structure_setting
    foreign key (strategy_market_structure_setting_id) references strategy_market_structure_settings (id);
alter table market_structures add constraint uk_market_structure_owner
    unique (instrument_id, strategy_market_structure_setting_id, window_end_at);
create index ix_market_structure_latest
    on market_structures (instrument_id, strategy_market_structure_setting_id, window_end_at desc);

-- 4. Реестры конфигураций уходят.
drop table indicator_configs;
drop table market_structure_configs;
