-- Шаг 4: команды и их жизненный цикл. Runtime graph сделки —
-- deals (граф-root) + orders / attached_algo_orders / algo_orders /
-- positions (по deal_id / order_id) + deal_action_states (операционное
-- состояние исполнения StrategyAction). Денежные/процентные величины —
-- numeric(36,18); enum'ы — строкой; время — UTC (timestamptz);
-- condition / target / last_error / linked_order_external_ids — jsonb;
-- имена таблиц во множественном числе. Логика финализации PnL Deal —
-- шаг 7 (поля уже есть). Схема — docs/models/domain/aggregate/Deal.md,
-- docs/models/domain/core/{Order,AlgoOrder,Position}.md,
-- docs/models/domain/other/DealActionState.md.

create table deals (
    id                     bigint generated by default as identity primary key,
    internal_id            varchar(64)  not null,
    instrument_id          bigint       not null,
    strategy_detail_id     bigint       not null,
    status                 varchar(32)  not null,
    direction              varchar(16)  not null,
    entry_reason           varchar(32),
    entry_step_type        varchar(32),
    shutdown_reason        varchar(32),
    close_reason           varchar(32),
    result_profit          numeric(36, 18),
    result_profit_currency varchar(16),
    created_at             timestamptz,
    created_by             varchar(64),
    modified_at            timestamptz,
    modified_by            varchar(64),
    external_created_at    timestamptz,
    external_modified_at   timestamptz,
    constraint uk_deal_internal_id unique (internal_id),
    constraint fk_deal_instrument foreign key (instrument_id) references instruments (id),
    constraint fk_deal_strategy_detail foreign key (strategy_detail_id) references strategy_details (id)
);

create table orders (
    id                     bigint generated by default as identity primary key,
    deal_id                bigint       not null,
    internal_id            varchar(64)  not null,
    external_id            varchar(64),
    status                 varchar(32)  not null,
    close_reason           varchar(32),
    type                   varchar(32)  not null,
    side                   varchar(16),
    external_status        varchar(32),
    price                  numeric(36, 18),
    size                   numeric(36, 18),
    accumulated_fill_size  numeric(36, 18),
    average_price          numeric(36, 18),
    fee                    numeric(36, 18),
    position_reducing_only boolean,
    replaces_internal_id   varchar(64),
    created_at             timestamptz,
    created_by             varchar(64),
    modified_at            timestamptz,
    modified_by            varchar(64),
    external_created_at    timestamptz,
    external_modified_at   timestamptz,
    constraint uk_order_internal_id unique (internal_id),
    constraint fk_order_deal foreign key (deal_id) references deals (id)
);

create table attached_algo_orders (
    id                      bigint generated by default as identity primary key,
    order_id                bigint       not null,
    internal_id             varchar(64)  not null,
    external_attached_id    varchar(64),
    external_id             varchar(64),
    status                  varchar(32)  not null,
    close_reason            varchar(32),
    type                    varchar(32)  not null,
    external_status         varchar(32),
    external_type           varchar(32),
    size                    numeric(36, 18),
    stop_loss_trigger_price numeric(36, 18),
    created_at              timestamptz,
    created_by              varchar(64),
    modified_at             timestamptz,
    modified_by             varchar(64),
    external_created_at     timestamptz,
    external_modified_at    timestamptz,
    constraint uk_attached_algo_order_internal_id unique (internal_id),
    constraint fk_attached_algo_order_order foreign key (order_id) references orders (id)
);

create table algo_orders (
    id                        bigint generated by default as identity primary key,
    deal_id                   bigint       not null,
    internal_id               varchar(64)  not null,
    external_id               varchar(64),
    status                    varchar(32)  not null,
    close_reason              varchar(32),
    condition_type            varchar(32)  not null,
    condition                 jsonb,
    size                      numeric(36, 18),
    direction                 varchar(16),
    position_reducing_only    boolean,
    replaces_internal_id      varchar(64),
    external_status           varchar(32),
    fail_code                 varchar(32),
    external_size             numeric(36, 18),
    external_price            numeric(36, 18),
    external_trigger_time     timestamptz,
    linked_order_external_ids jsonb,
    created_at                timestamptz,
    created_by                varchar(64),
    modified_at               timestamptz,
    modified_by               varchar(64),
    external_created_at       timestamptz,
    external_modified_at      timestamptz,
    constraint uk_algo_order_internal_id unique (internal_id),
    constraint fk_algo_order_deal foreign key (deal_id) references deals (id)
);

create table positions (
    id                           bigint generated by default as identity primary key,
    deal_id                      bigint      not null,
    external_id                  varchar(64),
    status                       varchar(32) not null,
    close_reason                 varchar(32),
    direction                    varchar(16),
    external_size                numeric(36, 18),
    external_average_entry_price numeric(36, 18),
    external_mark_price          numeric(36, 18),
    external_liquidation_price   numeric(36, 18),
    external_margin              numeric(36, 18),
    external_unrealized_profit   numeric(36, 18),
    created_at                   timestamptz,
    created_by                   varchar(64),
    modified_at                  timestamptz,
    modified_by                  varchar(64),
    external_created_at          timestamptz,
    external_modified_at         timestamptz,
    -- ≤1 позиция на сделку (инвариант Position.md).
    constraint uk_position_deal unique (deal_id),
    constraint fk_position_deal foreign key (deal_id) references deals (id)
);

create table deal_action_states (
    id                 bigint generated by default as identity primary key,
    deal_id            bigint      not null,
    strategy_action_id bigint      not null,
    status             varchar(32) not null,
    target             jsonb,
    attempt_count      integer,
    max_attempts       integer,
    next_retry_at      timestamptz,
    last_error         jsonb,
    -- Идемпотентность исполнения: одно состояние на действие в рамках сделки.
    constraint uk_deal_action_state_deal_action unique (deal_id, strategy_action_id),
    constraint fk_deal_action_state_strategy_action foreign key (strategy_action_id)
        references strategy_actions (id)
);
